fix error due to removal of 'soft_unicode' in module MarkupSafe
When running 'docker compose up', the following error is displayed: ImportError: cannot import name 'soft_unicode' from 'markupsafe'. 

This issue is caused because 'soft_unicode' was removed form MarkupSafe. By downgrading MarkupSafe to version 2.0.1 this problem can be solved.